version: "3"
services:
  flask-app:
    build:
      dockerfile: docker/flask/Dockerfile
      context: .
    ports:
      - 5000:5000
    depends_on:
      - redis-unstable
      - redis-stack

  flask-nginx:
    build:
      dockerfile: docker/nginx/Dockerfile
      context: .
    ports:
      - 80:80
    depends_on:
      - flask-app

  redis-unstable:
    build:
      dockerfile: docker/redis/Dockerfile
      context: .
    ports:
      - 6379:6379

  redis-stack:
    build:
      dockerfile: docker/redis-stack/Dockerfile
      context: .
    ports:
      - 6378:6379